# Advent of Code 2021 Day 1
[link](https://adventofcode.com/2021/day/1)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#read-input" data-toc-modified-id="read-input-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>read input</a></span><ul class="toc-item"><li><span><a href="#parse_input" data-toc-modified-id="parse_input-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>parse_input</a></span></li><li><span><a href="#input_sample_1" data-toc-modified-id="input_sample_1-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>input_sample_1</a></span></li><li><span><a href="#input_puzzle" data-toc-modified-id="input_puzzle-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>input_puzzle</a></span></li></ul></li><li><span><a href="#part-1" data-toc-modified-id="part-1-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>part 1</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li><li><span><a href="#part-2" data-toc-modified-id="part-2-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>part 2</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li></ul></div>

In [ ]:
# using Combinatorics
# using DataStructures
# using OffsetArrays
# using Mods

## read input

### parse_input

In [1]:
function parse_input(filename) 
    lines = parse_line.(readlines(filename))
end

parse_input (generic function with 1 method)

In [47]:
function parse_line(line)
    String.(split(line, ""))
end

parse_line (generic function with 1 method)

### input_sample_1

In [48]:
input_sample_1 = parse_input("input_sample_1.txt")

12-element Vector{Vector{String}}:
 ["0", "0", "1", "0", "0"]
 ["1", "1", "1", "1", "0"]
 ["1", "0", "1", "1", "0"]
 ["1", "0", "1", "1", "1"]
 ["1", "0", "1", "0", "1"]
 ["0", "1", "1", "1", "1"]
 ["0", "0", "1", "1", "1"]
 ["1", "1", "1", "0", "0"]
 ["1", "0", "0", "0", "0"]
 ["1", "1", "0", "0", "1"]
 ["0", "0", "0", "1", "0"]
 ["0", "1", "0", "1", "0"]

### input_puzzle

In [49]:
input_puzzle = parse_input("input_puzzle.txt")

1000-element Vector{Vector{String}}:
 ["0", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "1"]
 ["1", "1", "0", "0", "1", "0", "0", "1", "0", "0", "0", "1"]
 ["1", "1", "1", "0", "1", "1", "1", "1", "1", "1", "1", "1"]
 ["1", "1", "0", "0", "1", "1", "0", "1", "0", "1", "0", "0"]
 ["1", "1", "1", "1", "0", "0", "0", "0", "0", "0", "1", "1"]
 ["0", "1", "0", "1", "0", "1", "0", "0", "1", "0", "0", "1"]
 ["0", "1", "0", "1", "0", "1", "0", "0", "0", "0", "1", "0"]
 ["1", "0", "0", "1", "1", "1", "1", "0", "1", "0", "0", "0"]
 ["1", "1", "0", "1", "1", "0", "1", "0", "1", "1", "1", "0"]
 ["0", "0", "1", "0", "0", "1", "1", "0", "1", "0", "0", "0"]
 ["1", "0", "1", "1", "0", "0", "1", "0", "0", "1", "1", "0"]
 ["1", "0", "1", "0", "0", "1", "1", "0", "0", "1", "1", "0"]
 ["1", "0", "1", "1", "1", "0", "0", "0", "0", "1", "1", "0"]
 ⋮
 ["0", "1", "0", "1", "0", "1", "1", "1", "0", "1", "1", "1"]
 ["1", "1", "1", "1", "0", "0", "1", "0", "1", "0", "1", "1"]
 ["1", "0", "1", "1", "0", "1"

## part 1

In [66]:
ins = input_puzzle

count0 = zeros(Int, length(ins[1]))
count1 = zeros(Int, length(ins[1]))
for i in 1:length(ins[1])
    for v in ins
        if v[i] == "0"
            count0[i] += 1
        else
            count1[i] += 1
        end
    end
end
return count0, count1

([488, 507, 495, 504, 507, 493, 513, 507, 495, 513, 492, 491], [512, 493, 505, 496, 493, 507, 487, 493, 505, 487, 508, 509])

In [67]:
gamma = String[]
for i in 1:length(ins[1])
    push!(gamma, (count0[i] > count1[i]) ? "0" : "1")
end
gamma_num = parse(Int, join(gamma), base=2)

2635

In [68]:
epsilon = String[]
for i in 1:length(ins[1])
    push!(epsilon, (count0[i] > count1[i]) ? "1" : "0")
end
epsilon_num = parse(Int, join(epsilon), base=2)


1460

In [69]:
epsilon

12-element Vector{String}:
 "0"
 "1"
 "0"
 "1"
 "1"
 "0"
 "1"
 "1"
 "0"
 "1"
 "0"
 "0"

In [76]:
gamma_num * epsilon_num

3847100

### answer

In [50]:
@time @info(
        "part 1 answer",
        ans = move_part1(input_puzzle),
    )

  0.108448 seconds (201.22 k allocations: 12.224 MiB, 8.62% gc time, 98.80% compilation time)


┌ Info: part 1 answer
│   ans = 1561344
└ @ Main In[50]:1


## part 2

In [71]:
oxy_v = copy(ins)

for i in 1:length(ins[1])    
    if length(oxy_v) == 1
        return oxy_v
    end
    
    new_oxy_v = []
    
    c0 = 0
    c1 = 0
    for v in oxy_v
        if v[i] == "0"
            c0 += 1
        else
            c1 += 1
        end
    end
    
    x = c0 > c1 ? "0" : "1"

    
    for v in oxy_v
        if v[i] == x
            push!(new_oxy_v, v)
        end
    end
    oxy_v = new_oxy_v
end
return oxy_v

1-element Vector{Any}:
 ["1", "0", "1", "0", "1", "0", "1", "0", "1", "1", "1", "1"]

In [72]:
oxy = parse(Int, join(oxy_v[1]), base=2)

2735

In [73]:
co_v = copy(ins)

for i in 1:length(ins[1])
    if length(co_v) == 1
        return co_v
    end
    
    new_co_v = []
    
    c0 = 0
    c1 = 0
    for v in co_v
        if v[i] == "0"
            c0 += 1
        else
            c1 += 1
        end
    end
    
    x = c0 > c1 ? "1" : "0"

    
    for v in co_v
        if v[i] == x
            push!(new_co_v, v)
        end
    end
    co_v = new_co_v
end
return co_v

1-element Vector{Any}:
 ["0", "1", "0", "1", "1", "1", "0", "1", "1", "1", "0", "1"]

In [74]:
co = parse(Int, join(co_v[1]), base=2)

1501

In [75]:
oxy * co

4105235

In [55]:
function move_part2(inputs)
    c = [0, 0]
    aim = 0
    for i in inputs
        if i.d == "forward"
            c[1] += i.m
            c[2] += i.m * aim
        elseif i.d == "down"
            aim += i.m
        else  # i.d == "up"
            aim -= i.m
        end
    end
    return prod(c)
end

move_part2 (generic function with 1 method)

In [56]:
move_part2(input_sample_1)

900

### answer

In [57]:
@time @info(
        "part 2 answer",
        ans = move_part2(input_puzzle),
    )

  0.000133 seconds (62 allocations: 2.328 KiB)


┌ Info: part 2 answer
│   ans = 1848454425
└ @ Main In[57]:1
