# Advent of Code 2021 Day 5
[link](https://adventofcode.com/2021/day/5)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#helpers" data-toc-modified-id="helpers-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>helpers</a></span></li><li><span><a href="#read-input" data-toc-modified-id="read-input-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>read input</a></span><ul class="toc-item"><li><span><a href="#parse_input" data-toc-modified-id="parse_input-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>parse_input</a></span></li><li><span><a href="#ips1-:=-input-puzzle-sample-1" data-toc-modified-id="ips1-:=-input-puzzle-sample-1-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>ips1 := input puzzle sample 1</a></span></li><li><span><a href="#ipa-:=-input-puzzle-actual" data-toc-modified-id="ipa-:=-input-puzzle-actual-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>ipa := input puzzle actual</a></span></li></ul></li><li><span><a href="#part-1" data-toc-modified-id="part-1-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>part 1</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li><li><span><a href="#part-2" data-toc-modified-id="part-2-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>part 2</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li></ul></div>

In [22]:
# using Combinatorics
# using DataStructures
using OffsetArrays
# using Mods

## helpers

In [ ]:
"A"[1]

In [ ]:
parse(Int, "123ad4", base=16)

In [1]:
CI = CartesianIndex

CartesianIndex

In [4]:
CartesianIndex.(1, 2:3, 5:6)

2-element Vector{CartesianIndex{3}}:
 CartesianIndex(1, 2, 5)
 CartesianIndex(1, 3, 6)

## read input

### parse_input

In [8]:
function parse_input(f) 
    line = readlines(f)[1]
    parse_line(line)
end

parse_input (generic function with 1 method)

In [6]:
function parse_line(l)
    parse.(Int, split(l, ','))
end

parse_line (generic function with 1 method)

### ips1 := input puzzle sample 1

In [9]:
ips1 = parse_input("ips1.txt")

5-element Vector{Int64}:
 3
 4
 3
 1
 2

### ipa := input puzzle actual

In [10]:
ipa = parse_input("ipa.txt")

300-element Vector{Int64}:
 3
 1
 5
 4
 4
 4
 5
 3
 4
 4
 1
 4
 2
 ⋮
 1
 3
 4
 1
 1
 4
 5
 5
 2
 1
 3
 3

## part 1

In [14]:
function next(v::Vector{Int})
    v = deepcopy(v)
    counter = 0
    for i in 1:length(v)
        if v[i] == 0
            v[i] = 6
            counter += 1
        else
            v[i] -= 1
        end
    end
    append!(v, [8 for _ in 1:counter])
    
    return v
end

next (generic function with 1 method)

In [16]:
next(next(ips1))

6-element Vector{Int64}:
 1
 2
 1
 6
 0
 8

In [19]:
function result1(ip; n)
    for i in 1:n
        ip = next(ip)
    end
    return length(ip)
end

result1 (generic function with 1 method)

In [20]:
result1(ips1; n=18)

26

### answer

In [21]:
@time @info(
    "part 1 answer",
    result1(ips1; n = 18),
    result1(ipa; n = 80),
)

  0.129790 seconds (172.88 k allocations: 70.995 MiB, 5.14% gc time, 69.02% compilation time)


┌ Info: part 1 answer
│   result1(ips1; n = 18) = 26
│   result1(ipa; n = 80) = 345793
└ @ Main In[21]:1


## part 2

In [29]:
fish_count = zeros(Int, (0:8, 0:256))
fish_count[:, 0] .= 1

1

In [40]:
for day in 1:256
    for state in 0:8
        if state == 0
            fish_count[state, day] = fish_count[6, day - 1] + fish_count[8, day - 1]
        else
            fish_count[state, day] = fish_count[state - 1, day - 1]
        end
    end
end

In [42]:
sum([fish_count[s, 256] for s in ipa])

1572643095893

In [ ]:
function result2(ip)
    ip
end

### answer

In [ ]:
@time @info(
    "part 2 answer",
    result2(ips1),
    result2(ipa),
    )