# Advent of Code 2021 Day 5
[link](https://adventofcode.com/2021/day/5)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#helpers" data-toc-modified-id="helpers-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>helpers</a></span></li><li><span><a href="#read-input" data-toc-modified-id="read-input-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>read input</a></span><ul class="toc-item"><li><span><a href="#parse_input" data-toc-modified-id="parse_input-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>parse_input</a></span></li><li><span><a href="#ips1-:=-input-puzzle-sample-1" data-toc-modified-id="ips1-:=-input-puzzle-sample-1-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>ips1 := input puzzle sample 1</a></span></li><li><span><a href="#ipa-:=-input-puzzle-actual" data-toc-modified-id="ipa-:=-input-puzzle-actual-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>ipa := input puzzle actual</a></span></li></ul></li><li><span><a href="#part-1" data-toc-modified-id="part-1-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>part 1</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li><li><span><a href="#part-2" data-toc-modified-id="part-2-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>part 2</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li></ul></div>

In [131]:
# using Combinatorics
# using DataStructures
using OffsetArrays
# using Mods

## helpers

In [177]:
"A"[1]

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [ ]:
parse(Int, "123ad4", base=16)

In [159]:
CI = CartesianIndex

CartesianIndex

In [124]:
CartesianIndex.(1, 2:3, 5:6)

2-element Vector{CartesianIndex{3}}:
 CartesianIndex(1, 2, 5)
 CartesianIndex(1, 3, 6)

## read input

### parse_input

In [3]:
function parse_input(f) 
    lines = parse_coor.(readlines(f))
end

parse_input (generic function with 1 method)

In [172]:
function parse_coor(s)
    m = match(r"(\d+),(\d+) -> (\d+),(\d+)", s)
    return (
        c1 = CI(
            Int(m[1]),
            Int(m[2]),
        ),
        c2 = CI(
            Int(m[3]),
            Int(m[4]),
        ),
    )
end

parse_coor (generic function with 1 method)

### ips1 := input puzzle sample 1

In [173]:
ips1 = parse_input("ips1.txt")

10-element Vector{NamedTuple{(:c1, :c2), Tuple{CartesianIndex{2}, CartesianIndex{2}}}}:
 (c1 = CartesianIndex(0, 9), c2 = CartesianIndex(5, 9))
 (c1 = CartesianIndex(8, 0), c2 = CartesianIndex(0, 8))
 (c1 = CartesianIndex(9, 4), c2 = CartesianIndex(3, 4))
 (c1 = CartesianIndex(2, 2), c2 = CartesianIndex(2, 1))
 (c1 = CartesianIndex(7, 0), c2 = CartesianIndex(7, 4))
 (c1 = CartesianIndex(6, 4), c2 = CartesianIndex(2, 0))
 (c1 = CartesianIndex(0, 9), c2 = CartesianIndex(2, 9))
 (c1 = CartesianIndex(3, 4), c2 = CartesianIndex(1, 4))
 (c1 = CartesianIndex(0, 0), c2 = CartesianIndex(8, 8))
 (c1 = CartesianIndex(5, 5), c2 = CartesianIndex(8, 2))

### ipa := input puzzle actual

In [183]:
ipa = parse_input("ipa.txt")

500-element Vector{NamedTuple{(:c1, :c2), Tuple{CartesianIndex{2}, CartesianIndex{2}}}}:
 (c1 = CartesianIndex(348, 742), c2 = CartesianIndex(620, 742))
 (c1 = CartesianIndex(494, 864), c2 = CartesianIndex(494, 484))
 (c1 = CartesianIndex(193, 136), c2 = CartesianIndex(301, 136))
 (c1 = CartesianIndex(342, 692), c2 = CartesianIndex(342, 538))
 (c1 = CartesianIndex(234, 525), c2 = CartesianIndex(102, 393))
 (c1 = CartesianIndex(72, 964), c2 = CartesianIndex(847, 189))
 (c1 = CartesianIndex(639, 430), c2 = CartesianIndex(99, 970))
 (c1 = CartesianIndex(398, 791), c2 = CartesianIndex(398, 187))
 (c1 = CartesianIndex(181, 144), c2 = CartesianIndex(205, 168))
 (c1 = CartesianIndex(607, 617), c2 = CartesianIndex(416, 617))
 (c1 = CartesianIndex(98, 339), c2 = CartesianIndex(98, 437))
 (c1 = CartesianIndex(763, 119), c2 = CartesianIndex(176, 119))
 (c1 = CartesianIndex(450, 848), c2 = CartesianIndex(450, 664))
 ⋮
 (c1 = CartesianIndex(32, 312), c2 = CartesianIndex(833, 312))
 (c1 = CartesianI

## part 1

In [184]:
x_max(ip) = maximum(max(l.c1[2], l.c2[2]) for l in ip)
x_min(ip) = minimum(min(l.c1[2], l.c2[2]) for l in ip)
y_max(ip) = maximum(max(l.c1[1], l.c2[1]) for l in ip)
y_min(ip) = minimum(min(l.c1[1], l.c2[1]) for l in ip)

y_min (generic function with 1 method)

In [185]:
function get_starting_area(ip)
    return zeros(
        Int,
        (
            y_min(ip):y_max(ip),
            x_min(ip):x_max(ip),
        ),
    )
end

get_starting_area (generic function with 1 method)

In [85]:
function is_horizontal(l)
    return l.c1.x == l.c2.x
end

function is_vertical(l)
    return l.c1.y == l.c2.y
end

function is_diagonal(l)
    is_horizontal(l) && return false
    is_vertical(l) && return false
    return true
end

is_diagonal (generic function with 1 method)

In [91]:
@show is_horizontal.(ips1) is_vertical.(ips1) is_diagonal.(ips1);

is_horizontal.(ips1) = Bool[0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
is_vertical.(ips1) = Bool[1, 0, 1, 0, 0, 0, 1, 1, 0, 0]
is_diagonal.(ips1) = Bool[0, 1, 0, 0, 0, 1, 0, 0, 1, 1]


In [106]:
function get_vertical_vents(l, n)
    area = get_starting_area(n)
    (; x, y) = l.c1
    x_step = sign(l.c2.y - l.c1.y)
    steps = abs(l.c2.y - l.c1.y)
    
    for i in 0:steps
        area[y + i * y_step, x] = 1
    end
    return area
end

get_horizontal_vents (generic function with 2 methods)

In [45]:
function get_horizontal_vents(l, n)
    area = get_starting_area(n)
    x = l.c1.x
    y = l.c1.y
    y_step = sign(l.c2.y - l.c1.y)
    steps = abs(l.c2.y - l.c1.y)
    
    @show x y y_step steps
    
    for i in 0:steps
        area[y + i * y_step, x] = 1
    end
    return area
end

get_horizontal_vents (generic function with 2 methods)

In [105]:
get_horizontal_vents(ips1[4], 10)

x = 3
y = 3
y_step = -1
steps = 1


10×10 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [72]:
function get_diagonal_vents(l, n)
    area = get_starting_area(n)
    x = l.c1.x
    y = l.c1.y
    x_step = sign(l.c2.x - l.c1.x)
    y_step = sign(l.c2.y - l.c1.y)
    steps = abs(l.c2.x - l.c1.x)
    
    @show x y x_step y_step steps
    
    for i in 0:steps
        area[y + y_step * i, x + x_step * i] = 1
    end
    return area
end

get_diagonal_vents (generic function with 1 method)

In [56]:
function count_dangerous(area)
    count(>(1), area)
end

count_dangerous (generic function with 1 method)

In [57]:
function result1(ip, n)
    area = get_starting_area(n)
    
    for l in filter(is_horizontal, ip)
        area .+= get_horizontal_vents(l, n)
    end
    
    for l in filter(is_vertical, ip)
        area .+= get_vertical_vents(l, n)
    end
    
    return count_dangerous(area)
end

result1 (generic function with 2 methods)

In [58]:
result1(ips1, 10)

5

### answer

In [59]:
@time @info(
    "part 1 answer",
    result1(ips1, 10),
    result1(ipa, 1000),
)

  0.715239 seconds (68.38 k allocations: 2.440 GiB, 19.76% gc time, 3.68% compilation time)


┌ Info: part 1 answer
│   result1(ips1, 10) = 5
│   result1(ipa, 1000) = 4826
└ @ Main In[59]:1


## part 2

In [74]:
function result2(ip, n)
    area = get_starting_area(n)
    
    for l in filter(is_horizontal, ip)
        area .+= get_horizontal_vents(l, n)
    end
    
    for l in filter(is_vertical, ip)
        area .+= get_vertical_vents(l, n)
    end
    
    for l in filter(is_diagonal, ip)
        area .+= get_diagonal_vents(l, n)
    end
    
    return count_dangerous(area)
end

result2 (generic function with 1 method)

### answer

In [75]:
@time @info(
    "part 2 answer",
    result2(ips1, 10),
    result2(ipa, 1000),
    )

x = 1
y = 9
x_step = 1
y_step = -1
steps = 8
x = 5
y = 7
x_step = -1
y_step = -1
steps = 4
x = 1
y = 1
x_step = 1
y_step = 1
steps = 8
x = 6
y = 6
x_step = -1
y_step = 1
steps = 3
x = 526
y = 235
x_step = -1
y_step = -1
steps = 132
x = 965
y = 73
x_step = -1
y_step = 1
steps = 775
x = 431
y = 640
x_step = 1
y_step = -1
steps = 540
x = 145
y = 182
x_step = 1
y_step = 1
steps = 24
x = 22
y = 158
x_step = 1
y_step = 1
steps = 248
x = 956
y = 43
x_step = -1
y_step = 1
steps = 914
x = 24
y = 170
x_step = 1
y_step = 1
steps = 104
x = 600
y = 939
x_step = 1
y_step = -1
steps = 269
x = 47
y = 914
x_step = 1
y_step = -1
steps = 455
x = 652
y = 179
x_step = -1
y_step = 1
steps = 462
x = 744
y = 184
x_step = -1
y_step = 1
steps = 314
x = 35
y = 943
x_step = 1
y_step = -1
steps = 555
x = 461
y = 34
x_step = 1
y_step = 1
steps = 423
x = 863
y = 343
x_step = 1
y_step = -1
steps = 92
x = 126
y = 867
x_step = 1
y_step = -1
steps = 715
x = 490
y = 796
x_step = 1
y_step = -1
steps = 196
x = 508
y = 900


┌ Info: part 2 answer
│   result2(ips1, 10) = 12
│   result2(ipa, 1000) = 16793
└ @ Main In[75]:1
