# Advent of Code 2020 Day 20
[link](https://adventofcode.com/2020/day/20)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#dependencies" data-toc-modified-id="dependencies-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>dependencies</a></span></li><li><span><a href="#read-input" data-toc-modified-id="read-input-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>read input</a></span></li><li><span><a href="#part-1" data-toc-modified-id="part-1-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>part 1</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li><li><span><a href="#part-2" data-toc-modified-id="part-2-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>part 2</a></span><ul class="toc-item"><li><span><a href="#answer" data-toc-modified-id="answer-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>answer</a></span></li></ul></li></ul></div>

## dependencies

In [6]:
using Combinatorics, DataStructures, JSON, OffsetArrays, Interact, Images, NBInclude, Lazy

Make use of the fact that all possible orientation is defined by how many 90degree rotation to the left should I do `r ∈ [0, 1, 2, 3]`, and whether to flip upside down, `f == -1` if yes, `f == 1` if not. This gives the following as the valid orientations.

In [466]:
orientations = [
    (r = 0, f = 1),
    (r = 1, f = 1),
    (r = 2, f = 1),
    (r = 3, f = 1),
    (r = 0, f = -1),
    (r = 1, f = -1),
    (r = 2, f = -1),
    (r = 3, f = -1),
]

8-element Array{NamedTuple{(:r, :f),Tuple{Int64,Int64}},1}:
 (r = 0, f = 1)
 (r = 1, f = 1)
 (r = 2, f = 1)
 (r = 3, f = 1)
 (r = 0, f = -1)
 (r = 1, f = -1)
 (r = 2, f = -1)
 (r = 3, f = -1)

## read input

In [652]:
monster = begin
    lines = readlines("monster.txt") .|> (l -> (==('#')).(collect(l)))
    return [lines[i][j] for i in eachindex(lines), j in eachindex(lines[1])]
end

3×20 Array{Bool,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0
 1  0  0  0  0  1  1  0  0  0  0  1  1  0  0  0  0  1  1  1
 0  1  0  0  1  0  0  1  0  0  1  0  0  1  0  0  1  0  0  0

In [161]:
function parse_group(lines)
    id = @>> begin
        match(r"Tile (\d+):", lines[1])[1]
        parse(Int)
    end
    
    tile = @>> begin
        [lines[i][j] for i in 2:length(lines), j in eachindex(lines[2])]
        map(==('#'))
    end
    
    return id => tile
end

parse_group (generic function with 1 method)

In [162]:
function parse_input(filename)
    Dict(
        @as lines read(filename, String) begin
            split(lines, "\n\n")
            split.(lines, "\n")
            parse_group.(lines)
        end
    )
end

parse_input (generic function with 1 method)

In [163]:
input_sample_1 = parse_input("input_sample_1.txt")

Dict{Int64,Array{Bool,2}} with 9 entries:
  2729 => Bool[0 0 … 0 1; 1 1 … 0 0; … ; 1 1 … 0 0; 1 0 … 1 0]
  1489 => Bool[1 1 … 0 0; 0 0 … 0 0; … ; 0 0 … 1 1; 1 1 … 0 0]
  2473 => Bool[1 0 … 1 0; 1 0 … 0 0; … ; 1 1 … 1 0; 0 0 … 1 0]
  3079 => Bool[1 0 … 1 0; 0 1 … 1 1; … ; 0 0 … 0 0; 0 0 … 0 0]
  2311 => Bool[0 0 … 1 0; 1 1 … 0 0; … ; 1 1 … 1 0; 0 0 … 1 1]
  1171 => Bool[1 1 … 1 0; 1 0 … 0 1; … ; 1 1 … 0 0; 0 0 … 0 0]
  2971 => Bool[0 0 … 0 1; 1 0 … 0 0; … ; 0 0 … 1 0; 0 0 … 0 1]
  1951 => Bool[1 0 … 1 0; 1 0 … 0 1; … ; 0 0 … 0 1; 1 0 … 0 0]
  1427 => Bool[1 1 … 0 0; 0 1 … 0 0; … ; 0 0 … 0 1; 0 0 … 1 0]

In [164]:
input_puzzle = parse_input("input_puzzle.txt")

Dict{Int64,Array{Bool,2}} with 144 entries:
  2803 => Bool[0 1 … 0 1; 1 0 … 1 0; … ; 1 0 … 0 0; 0 0 … 0 0]
  2837 => Bool[0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 1 … 1 0]
  2131 => Bool[1 1 … 1 0; 0 1 … 1 1; … ; 0 0 … 1 0; 0 1 … 1 0]
  1069 => Bool[0 0 … 0 0; 1 1 … 0 1; … ; 0 1 … 0 1; 1 0 … 0 0]
  2311 => Bool[1 0 … 1 0; 1 0 … 0 0; … ; 0 0 … 0 0; 1 1 … 1 0]
  2441 => Bool[0 0 … 1 1; 1 0 … 0 0; … ; 1 0 … 1 1; 1 0 … 1 0]
  2111 => Bool[0 0 … 0 0; 0 0 … 0 1; … ; 0 0 … 0 0; 0 1 … 0 0]
  3767 => Bool[0 1 … 1 1; 0 0 … 0 0; … ; 1 0 … 0 1; 0 0 … 1 0]
  1933 => Bool[0 1 … 0 0; 1 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 1 0]
  1741 => Bool[0 1 … 0 1; 1 0 … 1 1; … ; 0 0 … 0 1; 0 1 … 1 1]
  3203 => Bool[0 1 … 1 0; 0 0 … 1 0; … ; 1 0 … 0 0; 1 1 … 0 0]
  2939 => Bool[1 0 … 1 1; 0 1 … 0 1; … ; 1 1 … 0 0; 0 0 … 1 0]
  2381 => Bool[0 0 … 0 1; 0 0 … 0 0; … ; 0 0 … 0 1; 1 0 … 0 0]
  1579 => Bool[1 0 … 1 1; 0 0 … 1 1; … ; 0 0 … 0 0; 0 1 … 0 0]
  3559 => Bool[0 0 … 1 0; 1 1 … 0 1; … ; 0 0 … 0 1; 0 0 … 0 0]
  2273 => B

In [165]:
data = input_sample_1

Dict{Int64,Array{Bool,2}} with 9 entries:
  2729 => Bool[0 0 … 0 1; 1 1 … 0 0; … ; 1 1 … 0 0; 1 0 … 1 0]
  1489 => Bool[1 1 … 0 0; 0 0 … 0 0; … ; 0 0 … 1 1; 1 1 … 0 0]
  2473 => Bool[1 0 … 1 0; 1 0 … 0 0; … ; 1 1 … 1 0; 0 0 … 1 0]
  3079 => Bool[1 0 … 1 0; 0 1 … 1 1; … ; 0 0 … 0 0; 0 0 … 0 0]
  2311 => Bool[0 0 … 1 0; 1 1 … 0 0; … ; 1 1 … 1 0; 0 0 … 1 1]
  1171 => Bool[1 1 … 1 0; 1 0 … 0 1; … ; 1 1 … 0 0; 0 0 … 0 0]
  2971 => Bool[0 0 … 0 1; 1 0 … 0 0; … ; 0 0 … 1 0; 0 0 … 0 1]
  1951 => Bool[1 0 … 1 0; 1 0 … 0 1; … ; 0 0 … 0 1; 1 0 … 0 0]
  1427 => Bool[1 1 … 0 0; 0 1 … 0 0; … ; 0 0 … 0 1; 0 0 … 1 0]

## part 1

In [237]:
function match_border(border1, border2)
    return border1 == reverse(border2)
end

match_border (generic function with 1 method)

In [513]:
function border(tile, o::@NamedTuple{r::Int, f::Int})
    filp_func = (o.f == 1) ? identity : reverse
    
    all_borders = [
        reverse!(tile[end, :]),
        reverse!(tile[:, begin]),
        tile[begin, :],
        tile[:, end],
    ]
    
    return all_borders[mod1(o.r, 4)] |> filp_func
end

border (generic function with 6 methods)

In [468]:
function get_all_borders(data)
    return Dict(
        id => border.(Ref(tile), orientations)
        for (id, tile) in data
    )
end

get_all_borders (generic function with 1 method)

In [469]:
function unmatched_borders(id, all_borders)
    result = []
    for border in all_borders[id]
        is_matched = false
        for (other_id, other_borders) in all_borders
            (other_id == id) && continue
            if any(match_border.(Ref(border), other_borders))
                is_matched = true
                break
            end
        end
        is_matched || push!(result, border)
    end
    return id => result
end

unmatched_borders (generic function with 1 method)

### answer

In [470]:
function show_answer_report(data, ::Val{:part1})
    all_borders = get_all_borders(data)
    d = unmatched_borders.(keys(data), Ref(all_borders))
    @show corner_ids = [id for (id, ubs) in d if length(ubs) == 4]
    @info "Answer found." answer=prod(corner_ids)
    return
end

show_answer_report (generic function with 3 methods)

In [514]:
show_answer_report(input_sample_1, Val(:part1))

corner_ids = [id for (id, ubs) = d if length(ubs) == 4] = [3079, 1171, 2971, 1951]


┌ Info: Answer found.
│   answer = 20899048083289
└ @ Main In[470]:5


In [515]:
show_answer_report(input_puzzle, Val(:part1))

corner_ids = [id for (id, ubs) = d if length(ubs) == 4] = [2287, 3433, 3461, 3083]


┌ Info: Answer found.
│   answer = 83775126454273
└ @ Main In[470]:5


## part 2

In [475]:
function fit_tile(tile1, tile2)
    for o1 in orientations[1:4], o2 in orientations
        if match_border(border(tile1, o1), border(tile2, o2))
            return (; o1, o2)
        end
    end
end

fit_tile (generic function with 1 method)

In [516]:
fit_tile(data[1951], data[2729])

(o1 = (r = 3, f = 1), o2 = (r = 1, f = 1))

In [517]:
fit_tile(data[1951], data[2311])

(o1 = (r = 0, f = 1), o2 = (r = 2, f = 1))

In [478]:
function matchable_ids(id, all_borders)
    result = []
    borders = all_borders[id]
    for (other_id, other_borders) in all_borders
        (other_id == id) && continue
        if any(Iterators.product(borders, other_borders) .|> (((b1, b2),) -> match_border(b1, b2)))
            push!(result, other_id)
        end
    end
    return result
end

matchable_ids (generic function with 1 method)

In [522]:
function whats_right(id, all_borders, all_tiles; current_f = 1, exclusion_ids = Int[])
    ids = setdiff(
        matchable_ids(id, all_borders),
        exclusion_ids,
    )
    if length(ids) == 1
        fit = fit_tile(all_tiles[id], all_tiles[ids[1]])
        return (
            id = ids[1],
            r = mod(fit.o2.r - 2, 4),
            f = current_f * fit.o2.f,
        )
    end
    
    # else there are 2 choices, one right one down
    fit1 = fit_tile(all_tiles[id], all_tiles[ids[1]])
    fit2 = fit_tile(all_tiles[id], all_tiles[ids[2]])
    
    if mod(current_f * (fit1.o1.r - fit2.o1.r), 4) == 1
        return (
            id = ids[2],
            r = mod(fit2.o2.r - 2, 4),
            f = current_f * fit2.o2.f,
        )
    else
        return (
            id = ids[1],
            r = mod(fit1.o2.r - 2, 4),
            f = current_f * fit1.o2.f,
        )
    end
end

whats_right (generic function with 3 methods)

In [591]:
function whats_down(id, all_borders, all_tiles; current_f = 1, exclusion_ids = Int[])
    ids = setdiff(
        matchable_ids(id, all_borders),
        exclusion_ids,
    )
    if length(ids) == 1
        fit = fit_tile(all_tiles[id], all_tiles[ids[1]])
        return (
            id = ids[1],
            r = mod(fit.o2.r + current_f * fit.o2.f, 4),
            f = current_f * fit.o2.f,
        )
    end
    
    # else there are 2 choices, one right one down
    fit1 = fit_tile(all_tiles[id], all_tiles[ids[1]])
    fit2 = fit_tile(all_tiles[id], all_tiles[ids[2]])
    
    if mod(current_f * (fit1.o1.r - fit2.o1.r), 4) == 1
        return (
            id = ids[1],
            r = mod(fit1.o2.r + current_f * fit1.o2.f, 4),
            f = current_f * fit1.o2.f,
        )
    else
        return (
            id = ids[2],
            r = mod(fit2.o2.r + current_f * fit2.o2.f, 4),
            f = current_f * fit2.o2.f,
        )
    end
end

whats_down (generic function with 1 method)

In [539]:
aaaa = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [545]:
hcat(aaaa, aaaa, aaaa)

2×6 Array{Int64,2}:
 1  2  1  2  1  2
 3  4  3  4  3  4

In [602]:
function make_map(top_left_id, all_borders, all_tiles, sq_len)
    metas = Matrix{@NamedTuple{id::Int, r::Int, f::Int}}(undef, (sq_len, sq_len))
    
    next_id, _, _ = whats_right(top_left_id, all_borders, all_tiles)
    
    o, _ = fit_tile(all_tiles[top_left_id], all_tiles[next_id])
    metas[1, 1] = (id = top_left_id, o.r, o.f)
    
    for i in 2:sq_len
        current_id, _, current_f = metas[1, i - 1]
        exclusion_ids = getfield.(metas[1, 1:(i - 1)], :id)
        metas[1, i] = whats_right(
            current_id,
            all_borders,
            all_tiles;
            current_f,
            exclusion_ids,
        )
    end
    
    for j in 1:sq_len, i in 2:sq_len
        current_id, _, current_f = metas[i - 1, j]
        current_id
        exclusion_ids = getfield.(metas[1:(i - 1), 1:j], :id)
        metas[i, j] = whats_down(
            current_id,
            all_borders,
            all_tiles;
            current_f,
            exclusion_ids,
        )
    end
    
    return vcat(
        [
            hcat(
                [
                    ((id, r, f) = metas[i, j]; oriented_tile(trim_tile(all_tiles[id]), r, f))
                    for j in 1:sq_len
                ]...
            ) for i in 1:sq_len
        ]...
    )
end

make_map (generic function with 3 methods)

In [601]:
function trim_tile(tile)
    return tile[2:(end - 1), 2:(end - 1)]
end

trim_tile (generic function with 1 method)

In [585]:
function oriented_tile(tile, r, f)
    for i in 1:r
        tile = rotl90(tile)
    end
    tile = (f == 1) ? tile : reverse(tile, dims = 1)
    return tile 
end

oriented_tile (generic function with 1 method)

In [619]:
function has_sea_monster(map, monster)
    return monster == map .* monster
end

has_sea_monster (generic function with 2 methods)

In [749]:
true ⊻ true

false

In [760]:
function make_safe_map(map, monster)
    result = copy(map)
    
    x_len_monster = size(monster, 2)
    y_len_monster = size(monster, 1)
    x_range = size(map, 2) - x_len_monster + 1
    y_range = size(map, 1) - y_len_monster + 1
    
    for x in 1:x_range, y in 1:y_range
        map_slice = @view(map[y:(y+y_len_monster-1), x:(x+x_len_monster-1)])
        if has_sea_monster(map_slice, monster)
            result[y:(y+y_len_monster-1), x:(x+x_len_monster-1)] .⊻= monster
        end
    end
    return result
end

make_safe_map (generic function with 1 method)

### answer

In [654]:
function print_area(area, p=true)
    for i in axes(area, 1)
        for j in axes(area, 2)
            print(area[i, j] ? '#' : '.', ' ')
            p && (j % 8 == 0) && print(' ')
        end
        println()
        p && (i % 8 == 0) && println()
    end
end

print_area (generic function with 2 methods)

In [783]:
dump(@view(@view(aaaa[1:1, 1:2])[1, 2]))

SubArray{Int64,0,Array{Int64,2},Tuple{Int64,Int64},true}
  parent: Array{Int64}((2, 2)) [1 2; 3 4]
  indices: Tuple{Int64,Int64}
    1: Int64 1
    2: Int64 2
  offset1: Int64 2
  stride1: Int64 1


In [772]:
function show_answer_report(data, lens, ::Val{:part2})
    all_borders = get_all_borders(data)
    d = unmatched_borders.(keys(data), Ref(all_borders))
    corner_ids = [id for (id, ubs) in d if length(ubs) == 4]
    top_left_corner_id = corner_ids[1]
    map = make_map(top_left_corner_id, all_borders, data, lens)
    
#     print_area(map)
    
    # using the fact that only 1 orientation has sea monster
    for (r, f) in orientations
        safe_map = make_safe_map(map, oriented_tile(monster, r, f))
#         print_area(safe_map)
        
        if safe_map != map
        @show count(safe_map)
        end
    end
#     m = reverse(monster, dims=1)
#     print_area(m, false)
    
#     println()
    
#     map_slice = @view(map[6:8, 2:21])
#     print_area(map_slice, false)
    
    
#     @show has_sea_monster(map_slice, m)


#     mark_sea_monster(map, reverse(monster, dims=1), [])
    
    @info "Answer found." answer=1
end

show_answer_report (generic function with 3 methods)

In [773]:
show_answer_report(input_sample_1, 3, Val(:part2))

count(safe_map) = 273


┌ Info: Answer found.
│   answer = 1
└ @ Main In[772]:33


In [774]:
show_answer_report(input_puzzle, 12, Val(:part2))

count(safe_map) = 1993


┌ Info: Answer found.
│   answer = 1
└ @ Main In[772]:33
